name: Frontend

on:
  push:
    branches:
      - "!dependabot/**/docs/**"
  pull_request_target:
    branches:
      - "!dependabot/**/docs/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: apache-superset/cancel-workflow-runs@953e057
        with:
          token: ${{ github.token }}
          selfPreservation: false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: apache-superset/cached-dependencies@b90713b
        with:
          run: npm-install
      - name: lint
        working-directory: ./superset-frontend
        run: |
          npm run lint
          npm run prettier-check
      - name: unit tests
        working-directory: ./superset-frontend
        run: |
          npm run test -- --coverage
      - name: Upload code coverage
        working-directory: ./superset-frontend
        run: |
          bash <(curl -s https://codecov.io/bash) -cF javascript
