# Python Misc unit tests
name: Python Misc

on:
  push:
    branches:
      - "!dependabot/npm_and_yarn/**"
  pull_request:
    branches:
      - "!dependabot/npm_and_yarn/**"

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Cancel Previous Runs
        uses: apache-superset/cancel-workflow-runs@953e057
        with:
          token: ${{ github.token }}
          selfPreservation: false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: apache-superset/cached-dependencies@b90713b
        with:
          run: |
            apt-get-install
            pip-upgrade
            pip install -r requirements/testing.txt
      - name: pylint
        # `-j 0` run Pylint in parallel
        run: pylint -j 0 superset

  pre-commit:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Cancel Previous Runs
        uses: apache-superset/cancel-workflow-runs@953e057
        with:
          token: ${{ github.token }}
          selfPreservation: false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: apache-superset/cached-dependencies@b90713b
        with:
          run: |
            apt-get-install
            pip-upgrade
            pip install -r requirements/integration.txt
      - name: pre-commit
        run: pre-commit run --all-files

  babel-extract:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Cancel Previous Runs
        uses: apache-superset/cancel-workflow-runs@953e057
        with:
          token: ${{ github.token }}
          selfPreservation: false
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: apache-superset/cached-dependencies@b90713b
        with:
          run: |
            apt-get-install
            pip-upgrade
            pip install -r requirements/base.txt
      - name: Test babel extraction
        run: flask fab babel-extract --target superset/translations --output superset/translations/messages.pot --config superset/translations/babel.cfg -k _,__,t,tn,tct
