name: E2E

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome']
    env:
      SUPERSET_CONFIG: tests.superset_test_config
      SUPERSET__SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset@127.0.0.1:15432/superset
      PYTHONPATH: ${{ github.workspace }}
      REDIS_PORT: 16379
      CI: github-actions
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    services:
      postgres:
        image: postgres:10-alpine
        env:
          POSTGRES_USER: superset
          POSTGRES_PASSWORD: superset
        ports:
          - 15432:5432
      redis:
        image: redis:5-alpine
        ports:
          - 16379:6379
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      uses: apache-superset/cached-dependencies@1d9cb401cfac282356e990a15e98bf05faae1e91
      with:
        run: |
          npm-install && npm-build
          pip-install && setup-postgres && testdata
          cypress-install
    - name: Cypress run all
      env:
        CYPRESS_GROUP: default
        CYPRESS_PATH: 'cypress/integration/*/*'
      run: |
        flask run -p 8081 --no-debugger &
        sleep 2 # wait for the Flask app to start
        cd ${{ github.workspace }}/superset-frontend/cypress-base/
        npm run cypress -- run \
          --browser ${{ matrix.browser }} --spec "${{ env.CYPRESS_PATH }}" \
          --record --group "${{ env.CYPRESS_GROUP }}" \
          --ci-build-id ${{ github.event_name }}-${{ github.run_id }}
    # Follow step relies on previously installed Cypress
    - name: Cypress run SQL Lab (with backend persist)
      env:
        SUPERSET_CONFIG: tests.superset_test_config_sqllab_backend_persist
        CYPRESS_GROUP: backend persist
        CYPRESS_PATH: 'cypress/integration/sqllab/*'
      run: |
        killall python # exit the running Flask app
        flask run -p 8081 --no-debugger &
        sleep 2 # wait for the Flask app to start
        cd ${{ github.workspace }}/superset-frontend/cypress-base/
        npm run cypress -- run \
          --browser ${{ matrix.browser }} --spec "${{ env.CYPRESS_PATH }}" \
          --record --group "${{ env.CYPRESS_GROUP }}" \
          --ci-build-id ${{ github.event_name }}-${{ github.run_id }}
