name: Frontend

on:
  push:
    branches: [ master ]
    paths:
    - superset-frontend/src/*
    - superset-frontend/spec/**/*
    - superset-frontend/*.js
    - superset-frontend/*.json
  pull_request:
    paths:
    - superset-frontend/src/*
    - superset-frontend/spec/**/*
    - superset-frontend/*.js
    - superset-frontend/*.json

jobs:
  frontend-build:
    name: build
    runs-on: ubuntu-latest
    env:
      CI: github-actions
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      uses: ktmud/cached-dependencies@v1
      with:
        run: npm-install
    - name: eslint
      working-directory: ./superset-frontend
      run: |
        npm run lint
    - name: unit tests
      working-directory: ./superset-frontend
      run: |
        npm run test -- --coverage
    - name: Upload code coverage
      working-directory: ./superset-frontend
      run: |
        bash <(curl -s https://codecov.io/bash)
